path:
  load_dir: Y:\240608_FXS\raw_data\h5\type=raw
  save_dir: Y:\240608_FXS\raw_data\h5\type=raw
  image_dir: Image
  param_dir: DataParameter2
  mat_dir: Mat_files
  npz_dir: Npz_files
  tif_dir: Tif_files
param:
  hutch: eh1
  detector: jungfrau2
  xray: HX
  pump_setting: 15HZ
  x1: 0
  x2: 1
  y1: 2
  y2: 3
  sdd: 1.3
  dps: 7.5e-05
  beam_energy: 9.7
