runs:
  - 142

path:
  log: ./logs

  load_dir: Y:\240608_FXS\raw_data\h5\type=raw
  # load_dir: /mnt/y/240608_FXS/raw_data/h5/type=raw
  analysis_dir: Y:\240608_FXS\analysis_data
  # analysis_dir: /mnt/y/240608_FXS/analysis_data

  output_dir: ${path.analysis_dir}/output_data
  mat_dir: ${path.analysis_dir}/mat_files2
  processed_dir: ${path.analysis_dir}/processed_data

param:
  hutch: eh1
  detector: jungfrau2
  xray: HX
  pump_setting: 15HZ
  x1: 0
  x2: 1
  y1: 2
  y2: 3
  sdd: 1.3
  dps: 7.5e-05
  beam_energy: 9.7
